name = "kobastudio-api"
compatibility_date = "2024-12-01"
main = "worker.js"

routes = [
  { pattern = "api.kobastudio.cl/*", zone_name = "kobastudio.cl" }
]

[env.production]
routes = [
  { pattern = "api.kobastudio.cl/*", zone_name = "kobastudio.cl" }
]

vars = { NODE_ENV = "production" }
